//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResortMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLogin
    {
        public string LoginID { get; set; }
        public string LoginPassword { get; set; }
    }
}
